/** Curated starting points the user can apply with a single click. */
import type { CalculatorDesign, PresetName } from "@/config/design";

interface Preset {
  swatch: readonly string[];
  values: Partial<CalculatorDesign>;
}

export const PRESETS: Record<PresetName, Preset> = {
  Classic: {
    swatch: ["#ffffff", "#f08a3c", "#f1efea"],
    values: {
      stageBg: "#dcd9d2",
      bodyBg: "#ffffff",
      displayBg: "#f4f3f0",
      displayText: "#1a1916",
      digitBg: "#f1efea",
      digitText: "#1a1916",
      opBg: "#f08a3c",
      opText: "#ffffff",
      fnBg: "#e4e1da",
      fnText: "#1a1916",
      eqBg: "#f08a3c",
      eqText: "#ffffff",
      opBorder: "#f08a3c",
      borderCol: "#e2dfd8",
      font: "Sora",
      shape: "Rounded",
      shadow: "soft",
      press: "push",
      borderW: 0,
      bodyRadius: 30,
      btnRadius: 18,
      gap: 10,
    },
  },
  Midnight: {
    swatch: ["#16161a", "#2c2c34", "#ffb000"],
    values: {
      stageBg: "#0c0c0e",
      bodyBg: "#16161a",
      displayBg: "#0e0e11",
      displayText: "#f5f3ee",
      digitBg: "#26262d",
      digitText: "#f5f3ee",
      opBg: "#ffb000",
      opText: "#16161a",
      fnBg: "#3a3a44",
      fnText: "#f5f3ee",
      eqBg: "#ffb000",
      eqText: "#16161a",
      opBorder: "#ffb000",
      borderCol: "#2c2c34",
      font: "Grotesk",
      shape: "Rounded",
      shadow: "soft",
      press: "push",
      borderW: 0,
      bodyRadius: 28,
      btnRadius: 16,
      gap: 9,
    },
  },
  Neumorph: {
    swatch: ["#e4e9f0", "#e4e9f0", "#6d7fd6"],
    values: {
      stageBg: "#e4e9f0",
      bodyBg: "#e4e9f0",
      displayBg: "#e4e9f0",
      displayText: "#3a4256",
      digitBg: "#e4e9f0",
      digitText: "#5a6072",
      opBg: "#e4e9f0",
      opText: "#6d7fd6",
      fnBg: "#e4e9f0",
      fnText: "#9aa0b0",
      eqBg: "#6d7fd6",
      eqText: "#ffffff",
      opBorder: "#e4e9f0",
      borderCol: "#e4e9f0",
      font: "Sora",
      shape: "Rounded",
      shadow: "neu",
      press: "sink",
      borderW: 0,
      bodyRadius: 34,
      btnRadius: 18,
      gap: 14,
      bodyPad: 22,
    },
  },
  Brutalist: {
    swatch: ["#fff8e8", "#ffe600", "#111111"],
    values: {
      stageBg: "#fff3d6",
      bodyBg: "#fff8e8",
      displayBg: "#ffffff",
      displayText: "#111111",
      digitBg: "#ffffff",
      digitText: "#111111",
      opBg: "#ffe600",
      opText: "#111111",
      fnBg: "#d8d2c2",
      fnText: "#111111",
      eqBg: "#111111",
      eqText: "#ffffff",
      opBorder: "#111111",
      borderCol: "#111111",
      font: "Mono",
      shape: "Square",
      shadow: "hard",
      press: "pop",
      borderW: 3,
      bodyRadius: 6,
      btnRadius: 4,
      gap: 10,
    },
  },
  Candy: {
    swatch: ["#fff0f6", "#ff6fb5", "#7c6cf0"],
    values: {
      stageBg: "#ffe3ef",
      bodyBg: "#fff0f6",
      displayBg: "#ffffff",
      displayText: "#6b2a52",
      digitBg: "#ffe0ee",
      digitText: "#a03a73",
      opBg: "#ff6fb5",
      opText: "#ffffff",
      fnBg: "#ffd2e6",
      fnText: "#a03a73",
      eqBg: "#7c6cf0",
      eqText: "#ffffff",
      opBorder: "#ff6fb5",
      borderCol: "#ffd2e6",
      font: "Grotesk",
      shape: "Pill",
      shadow: "soft",
      press: "pop",
      borderW: 0,
      bodyRadius: 36,
      btnRadius: 30,
      gap: 11,
    },
  },
  Terminal: {
    swatch: ["#04140a", "#0a2a16", "#39ff7a"],
    values: {
      stageBg: "#02080a",
      bodyBg: "#04140a",
      displayBg: "#021008",
      displayText: "#39ff7a",
      digitBg: "#082817",
      digitText: "#39ff7a",
      opBg: "#0d3a22",
      opText: "#7dffae",
      fnBg: "#0a2415",
      fnText: "#39ff7a",
      eqBg: "#39ff7a",
      eqText: "#021008",
      opBorder: "#1f6b3f",
      borderCol: "#1f6b3f",
      font: "Mono",
      shape: "Square",
      shadow: "glow",
      press: "push",
      borderW: 1,
      bodyRadius: 8,
      btnRadius: 5,
      gap: 8,
    },
  },
};
